; Generated by the Python script
  MODULE Graphics
  
  ORG #B6D6
  ALIGN 2

cuboid
  word #B8A2, #B942, #B9E2, #BA5E, #BABA, #BB1E, #BB9A, #BC3A, #BCB6
  word #BD4A, #BDA8, #BDF2, #BE56, #BEC6, #BF2E, #BFA0, #C01C, #C098
  word #C114, #C19C, #C22C, #C290, #C2E8, #C358, #C3E8, #C470, #C504
  word #C5B0, #C62C, #C690, #C702, #C77E, #C7E2, #C846, #C8A2, #C914
  word #C97C, #CA04, #CA8C, #CAF4, #CB52, #CBBA, #CC42, #CCCA, #CD3C
  word #CDC4, #CE34, #CE98, #CF0C, #CF8E, #CFFE, #D06E, #D0DE, #D14E
  word #D1BE, #D252, #D2F2, #D36E, #D3E0, #D444, #D4CA, #D546, #D5C2
  word #D64A, #D69E, #D6F6, #D74E, #D7AC, #D814, #D886, #D8F8, #D974
  word #D9F0, #DA78, #DAF4, #DB58, #DBBC, #DC2C, #DCCA, #DD68, #DDF0
  word #DE84, #DEF6, #DF68, #DFE4, #E040, #E0A4, #E116, #E188, #E1FA

blocks
  word #B792, #B7D6
  word #B81A, #B85E


  ORG #B792
  ALIGN 2
sprites
  INCBIN "../data/sprites.bin"

  ORG #E258
  ALIGN 8
tiles
  INCBIN "../data/tiles.bin"

  ENDMODULE
